github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false

tasks:
  - init: ./scripts/bootstrap.sh
    command: make livehtml
        
ports:
  - port: 8000
    onOpen: open-preview
