github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: true
    addBadge: false

tasks:
  - name: Dependencies
  - init: ./scripts/bootstrap.sh
  - name: Autobuild Sever
    command: make livehtml
        
ports:
  - port: 8000
    onOpen: open-preview
