files:
  - source: /locales/zh_CN/**/api/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/reference/api/%original_file_name%
  - source: /locales/zh_CN/**/reference/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/reference/%original_file_name%
  - source: locales/en/LC_MESSAGES/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/%original_file_name%
  - source: locales/en/LC_MESSAGES/getting-started/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/getting-started/%original_file_name%
  - source: locales/en/LC_MESSAGES/getting-started/beginner/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/getting-started/beginner/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/install/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/install/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/deployment/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/deployment/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/tools/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/tools/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/about/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/about/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/faq/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/faq/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/tensor/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/tensor/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/functional/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/functional/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/data/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/data/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/module/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/module/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/autodiff/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/autodiff/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/optimizer/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/optimizer/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/serialization/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/serialization/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/hub/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/hub/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/dtr/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/dtr/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/distributed/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/distributed/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/quantization/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/quantization/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/amp/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/amp/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/profiler/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/profiler/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/model-development/jit/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/model-development/jit/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/deployment/traced_module/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/deployment/traced_module/%original_file_name%
  - source: locales/en/LC_MESSAGES/user-guide/deployment/lite/*.po
    translation: /locales/%locale_with_underscore%/LC_MESSAGES/user-guide/deployment/lite/%original_file_name%
