files:
  - source: /locales/zh_CN/**/api/*.po
    translation: /locales/%locale%/LC_MESSAGES/reference/api/%original_file_name%
  - source: /locales/zh_CN/**/reference/*.po
    translation: /locales/%locale%/LC_MESSAGES/reference/%original_file_name%
